### PR TITLE
Update standardiser to 0.1.9

### PR DESCRIPTION
**Pull request by simonbray**
We need the python3-compatible version for a tool.

@tsenapathi, I added myself as a maintainer, hope that's okay?

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by simonbray** [comment]
@conda-forge-admin, please rerender

**Comment by tsenapathi** [comment]
> 
> 
> We need the python3-compatible version for a tool.
> 
> @tsenapathi, I added myself as a maintainer, hope that's okay?
> 
> Checklist
> 
>     * [x]  Used a fork of the feedstock to propose changes
> 
>     * [x]  Bumped the build number (if the version is unchanged)
> 
>     * [x]  Reset the build number to `0` (if the version changed)
> 
>     * [ ]  [Re-rendered](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks) with the latest `conda-smithy` (Use the phrase `@conda-forge-admin, please rerender` in a comment in this PR for automated rerendering)
> 
>     * [x]  Ensured the license file is being packaged.

Thanks @simonbray!!

**Comment by simonbray** [comment]
Ready to merge I think

**Review by tsenapathi — APPROVED** [review]

**Comment by simonbray** [comment]
Cool, thanks Tharindu!

**Comment by tsenapathi** [comment]
> 
> 
> Cool, thanks Tharindu!
👍

**Pull request merged**
